### ISSUE TITLE
I cant use all of these cheats

### ISSUE THREAD

**Issue by willutgilugpiulg** [GooseterV/Blooket#1]
So now i'm on chromebook so i use the Javascript:fetch("https://raw.githubusercontent.com/GooseterV/Blooket/master/js/spoofer.js").then((res) => res.text().then((t) => eval(t)))
and i used it the first time and it worked and did what its supposed to do but now it wont open anything what am i doing wrong???

**Comment by GooseterV** [comment]
I’m on vacation right now and am positive I know the problem, I can fix it next week but I’m unable to right now, in the meantime it won’t be useable.

**Comment by GooseterV** [comment]
Ok, I’ve fixed it, wasn’t as difficult as i thought.
