### ISSUE TITLE
BookblookViewer.js not work

### ISSUE THREAD

**Issue by wolfgoo** [GooseterV/Blooket#2]
why!!!

**Comment by wolfgoo** [comment]
I need do some things

**Comment by bluejho11** [comment]
yea it is not working

**Comment by GooseterV** [comment]
Blooket now blocket cloudinary, I'm exploring fixes. For now you can copy the code directly and it should work.

**Comment by GooseterV** [comment]
Okay, everything is back up and running. Try copying the updated code.

**Comment by wolfgoo** [comment]
ok
