### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Eclipse-5214** [GooseterV/Blooket#32]
**Describe the bug**
the add blooks function throws this error

VM757:51 Uncaught TypeError: Cannot read properties of undefined (reading 'blookData')
    at <anonymous>:50:24

**To Reproduce**
1. Go to [Blooket]
2. Go to Blooks
3. Open up console (ctrl + shift + j)
4. Paste [addblooks.js] into console
5. [bug] happens

**Expected behavior**
it would spawn the blook

**Version**
[986c106](https://github.com/GooseterV/Blooket/commit/986c106ef1b4b0f96e7ce1ba20d6752c8ea9f2b8)

**Screenshots**

**Desktop**
 - Browser [chrome]

**Other**
Anything else you want to say

**Comment by GooseterV** [comment]
script is currently being updated to fix bug, will tell when finished

**Comment by Oplanatie** [comment]
How long should this fix last?

**Comment by GooseterV** [comment]
probably i can get it fixed tonight but If i don't tonight you might gotta wait unt sunday

**Comment by GooseterV** [comment]
but yeah expect it to fixed by tonight
