### ISSUE TITLE
Add Tokens Not Working

### ISSUE THREAD

**Issue by givemeusername199** [GooseterV/Blooket#33]
Everytime I use the addtokens.js in the console it doesnt work

1. Go to [Blooket]
2. Go to [MArket]
3. Open up console (ctrl + shift + j)
4. Paste [addtokens.js] into console
5. [bug] happens

**Expected behavior**
I expected the script to give me 500 tokens 
**Version**
What repository version is the bug in. Make sure it is a valid and non-deprecated version.

**Screenshots**

**Desktop**
Chrome

**Other**
I had 460 tokens instead of 500 left.

**Comment by Greenlio** [comment]
fixed @ commit https://github.com/GooseterV/Blooket/commit/87c7e7988f8b98a51ccc7c71d42d6b6602faa234 (click for info)
