### ISSUE TITLE
Add daily rewards (BUG)

### ISSUE THREAD

**Issue by DummyPotato** [GooseterV/Blooket#35]
**Describe the bug**
The add-rewards in network tab is almost the exact same as the one you made, and it doesn't work. Gives an error "PUT https://api.blooket.com/api/users/add-rewards 400". I've tried changing the code up, and even tried running it after a game, when some rewards get added.

**To Reproduce**
1. Go to [Blooket]
2. Go to [any page]
3. Open up console (ctrl + shift + j)
4. Paste [addReward.js] into console
5. [error] happens

**Expected behavior**
Add some tokens or XP to your account.

**Version**
Latest

**Screenshots**
Self explanitory, so not really needed.

**Desktop**
 - Browser [Chrome]

**Mobile Device**
Not tested

**Other**
Can you explain/fix/recommend anything on the script?

**Comment by Greenlio** [comment]
fixed @ commit https://github.com/GooseterV/Blooket/commit/87c7e7988f8b98a51ccc7c71d42d6b6602faa234 (click for info)

**Comment by DummyPotato** [comment]
aight works :)
