### ISSUE TITLE
Spam open pack doesnt work

### ISSUE THREAD

**Issue by DummyPotato** [GooseterV/Blooket#37]
**Describe the bug**
Running the script causes an error in the console:
PUT https://api.blooket.com/api/users/unlockblook

**To Reproduce**
1. Go to [Blooket]
2. Go to [any page]
3. Open up console (ctrl + shift + j)
4. Paste [spamOpenPack.js] into console
5. [error] happens

**Expected behavior**
Pack being spam opened.

**Version**
Newest

**Screenshots**
Not really needed

**Desktop**
 - Browser [chrome]

**Mobile Device**
not tested

**Other**
nope

**Comment by Greenlio** [comment]
🍔

**Comment by GooseterV** [comment]
fixed in latest update
