### ISSUE TITLE
Spoof Blooks

### ISSUE THREAD

**Issue by Wilke000** [GooseterV/Blooket#39]
Doesn't work

I try to do it but It does nothing, pls fix

Browser - Chrome

**Comment by GooseterV** [comment]
it does work
are you using it on the ./blooks page

**Comment by Wilke000** [comment]
yes and the choose blook page while I'm playing a game, both don't work

**Comment by Wilke000** [comment]
Here i'll send a video

**Comment by Wilke000** [comment]
nevermind i can't send a video...
<img width="399" alt="Screen Shot 2022-09-29 at 9 14 44 AM" src="https://user-images.githubusercontent.com/85253703/193041158-81946d96-45b6-4581-8ce5-34aa0bb4ff4d.png">

**Comment by GooseterV** [comment]
it only works on the books page, i don't know why the impression was made that it's used in game. If you want to send a screenshot of your console then that would be helpful instead of just saying "it's broken"

**Comment by Wilke000** [comment]
ok (I did have an uncommon equipped and it still didn't do anything, only equip a witch

https://user-images.githubusercontent.com/85253703/193042755-26c1c8f1-6632-4e6f-b96a-53815cfe0d6b.mov

**Comment by GooseterV** [comment]
nothing is broken about it and it works fine

**Comment by GooseterV** [comment]
did you read the instructions on using it before you used it

**Comment by Wilke000** [comment]
Yes i did it still doesn't work

**Comment by GooseterV** [comment]
i tested it yesterday and it works fine.
are you not clicking a blook after it sets your blook to the witch? if so that would cause it

**Comment by Wilke000** [comment]
Thats when it shows an error

**Comment by Wilke000** [comment]
<img width="618" alt="Screen Shot 2022-09-30 at 8 30 52 AM" src="https://user-images.githubusercontent.com/85253703/193270347-9e97ca3a-dfa7-42da-9b6f-f5b7332bf842.png">

**Comment by GooseterV** [comment]
i'm unable to reproduce the error

**Comment by Wilke000** [comment]
Yes i am

**Comment by Wilke000** [comment]
Like make a yt vid?

**Comment by TheBobCreator** [comment]
same

**Comment by Wilke000** [comment]
Wdym @TheBobCreator

**Comment by Greenlio** [comment]
https://user-images.githubusercontent.com/62725108/193427553-c3d3e8f0-e16f-44a4-b67c-f99167d430f2.mp4

**Comment by Wilke000** [comment]
IT IS FIXED TY

**Comment by Wilke000** [comment]
Wait the single add blook hack doesn't work either
