### ISSUE TITLE
Unlock all Parts

### ISSUE THREAD

**Issue by Wilke000** [GooseterV/Blooket#44]
It does show the parts, but when I reload the page the custom blook is not there

1. Go to the blooket stats page
2. Create a custom blook
3. Open up console
4. Paste unlockAllParts.js into console
5. Choose your parts that you don't have
6. Click save
7. Reload
8. It doesn't save

It is the newest/only version

https://user-images.githubusercontent.com/85253703/193632232-6f24213e-e9dc-44c8-85e6-cf90d73ad469.mov

 - Chrome

**Comment by Wilke000** [comment]
(The flash is me reloading)

**Comment by GooseterV** [comment]
It's not supposed to save your custom blook if you would read carefully.
https://github.com/GooseterV/Blooket/discussions/42#discussioncomment-3762602

**Comment by Wilke000** [comment]
bruh
