### ISSUE TITLE
SPAM OPEN WILL BAN

### ISSUE THREAD

**Issue by Wilke000** [GooseterV/Blooket#46]
Spam open will ban i just got banned on BOTH my accounts

**Comment by Wilke000** [comment]
Thats all u need to know

**Comment by Wilke000** [comment]
but i closed the page before the system could register it I think
But all-in-all it doesn't work

**Comment by GooseterV** [comment]
it does not ban you as I literally just used it and didn't get banned. the script also didn't even work so there's no possibility you could've gotten banned from a script that doesn't even work?
