### ISSUE TITLE
Someone is wrong, download a text file instead

### ISSUE THREAD

**Issue by Rookiehecker** [GooseterV/Blooket#5]
I always got a message like that while exporting wth

**Comment by Rookiehecker** [comment]
also wheres import blooks

**Comment by GooseterV** [comment]
For the issue, i'm not sure why it's happening and failing to copy, but you can still copy the contents of the text file.
For your request, it is impossible to do. Blooks are managed server side meaning you won't be able to import them.

**Comment by GooseterV** [comment]
@Rookiehecker
