### ISSUE TITLE
Add Blook won't stay.

### ISSUE THREAD

**Issue by TheR1000** [GooseterV/Blooket#50]
**Describe the bug**
When you reload, it goes away.

**To Reproduce**
1. Go to Blooket
2. Go to Blooks
3. Open up console (ctrl + shift + j)
4. Paste addblook.js into console
5. Reload
6. bug happens

**Expected behavior**
It should stay.

**Version**
Current as of posting

**Desktop**
Edge

**Comment by TheR1000** [comment]
Also spoofer doesn't stay.

**Comment by Wilke000** [comment]
It’s not supposed to

**Comment by Wilke000** [comment]
It’s server sided
It’s impossible to add blocks and save them
Please close issue

**Comment by Greenlio** [comment]
impossible, wont add, cant add. its temporary and a client-side spoof
