### ISSUE TITLE
Can you make the "Add Tokens" script a type where you don't have to open inspect? 

### ISSUE THREAD

**Issue by E10DezNuts** [GooseterV/Blooket#51]
Can you make it to where you can just type javascript: and paste code i url bar. Inspect is blocked for me.

**Comment by Wilke000** [comment]
What browser you on?

**Comment by E10DezNuts** [comment]
I am on chrome

**Comment by Wilke000** [comment]
Use safari

**Comment by GooseterV** [comment]
don't use safari, it is the worst possible browser to use. if you want to you can just paste the code after typing `jacascript:` in the searchbat

**Comment by VillainsRule4000** [comment]
agreed

**Comment by E10DezNuts** [comment]
That's the thing. It won't work when I type javascript:

**Comment by MadId1ot** [comment]
JUST MAKE A BOOK MARK AND EDIT IT TO A CUSTOM NAME AND 'javascript:[code]'! THAT EASY!

**Comment by Greenlio** [comment]
bookmarklets :stoics:

just run it through any web bookmarklet converter like [this one](https://mrcoles.com/bookmarklet/)
